project:
  type: website
  output-dir: docs

website:
  title: "Spatialism"
  site-url: https://lopezjimenezjesus.github.io
  description: "Geospatial Ecology"
  navbar:
    background: "#fff"
    right:
      - text: "About"
        file: index.qmd
      # - text: "Blog"
      #   file: index.qmd
      - text: "CV"
        file: cv.pdf
  page-footer: 
      left: "Copyright 2022, Jesús Jiménez" 
      right: 
        - icon: github
          href: https://github.com/lopezjimenezjesus
        - icon: linkedin
          href: https://www.linkedin.com/in/lopezjimenezjesus
        - icon: mailbox2
          href: mailto:lopezjimenezjesus@gmail.com
        - icon: file-earmark-text
          href: cv.pdf
format:
  html:
    theme: [litera, custom.scss]
    css: styles.css
    toc: true

editor: visual

