---
title: "James Tripp - CV"
---

## Experience

*Senior Research Software Engineer* - IT Services, University of Warwick

Oct 2021 - present

* Wrote software and consulted for research project across the University
* Designed and contributed to research infrastructure built on-prem and in Azure
* Promoted excellent software development practices through teaching and outreach

*Senior Academic Technologist* - Centre for Interdisciplinary Methodologies, University of Warwick

Jun 2019 - Oct 2021

* Taught technical labs on Machine Learning, Inferential Statistics and Digital Methods
* Built a Linux infrastructure for delivering teaching and research

*Academic Technologist* - Centre for Interdisciplinary Methodologies, University of Warwick

Dec 2015 - Jun 2021

Description

*Post-Doctoral Research Fellow*- Department of Psychology, University of Warwick

Oct 2013 - Sep 2019

Description

## Qualifications

**University of Warwick** PhD Psychology

**University of Warwick** BSc(Hons) Psychology

## References

Available on request